### ISSUE TITLE
Add info on when Inizio and Demoskop came together to one house

### ISSUE THREAD

**Issue by MansMeg** [MansMeg/SwedishPolls#111]

**Comment by StaffanBetner** [comment]
Det verkar vara så att Demoskop-mätningarna fr.o.m. november är att betrakta som en fortsättning på Inizio-serien?

Sista Aftonbladet/Inizio: https://www.aftonbladet.se/nyheter/samhalle/a/e8mweR/rekordhogt-stod-for-sd--knappar-in-pa-s

Metodredovisning:
> Undersökningen är gjord av Inizio på uppdrag av Aftonbladet inom ramen för Iniziopanelen som speglar svenska folket. Undersökningen omfattar 2 097 intervjuer 20–25 september och är genomförd som en webbundersökning. Frågan som ställdes var: “Vilket parti skulle du rösta på om det var riksdagsval i dag?”

Sista Expressen/Demoskop: https://www.expressen.se/nyheter/historisk-matning-s-och-sd-jamnstora-for-forsta-gangen/

Metodredovisning:
> Metod och urval: Telefonbaserade intervjuer utifrån befolkningsurval baserat på telefonnummer samt webbintervjuer i en panel som rekryteras bland besökare på drygt 400 socioekonomiskt stratifierade webbplatser. Att på eget initiativ anmäla sig till webbpanelen, så kallad självrekrytering, är inte möjligt.

Första Aftonbladet/Demoskop: https://www.aftonbladet.se/nyheter/samhalle/a/e8Rp6g/historisk-matning-nu-ar-sd-storst-i-sverige

Metodredovisning: 
> Undersökningen är gjord av Demoskop på uppdrag av Aftonbladet. Undersökningen är genomförd inom ramen för Iniziopanelen som speglar svenska folket samt en onlinepanel som rekryteras genom ett samarbete med drygt 400 webbplatser. Målgruppen är allmänheten 18 år och äldre. Undersökningen omfattar 2 048 intervjuer under perioden 4-13 november 2019 och är genomförd som en webbundersökning. Frågan som ställdes var:  “Vilket parti skulle du rösta på om det var riksdagsval i dag?”

**Comment by MansMeg** [comment]
Bra där! Jag tror inte det har någon praktisk effekt då det skedde så tidigt under mandatperioden och husbias och designeffekter skattas per mandatperiod. Men det kan vara värt att dubbelkolla.
