### ISSUE TITLE
Commit access

### ISSUE THREAD

**Issue by hjnilsson** [MansMeg/SwedishPolls#73]
Hej,

Jag (som driver https://val.digital ) och Viktor Tullgren (som driver http://pollofpolls.se ) skulle vilja använda data här som underlag till våra respektive sidor. En forutsättning för detta är att vi båda kan bidra med uppdateringar. Är det möjligt att ge oss commit access hit så vi kan göra det när nya undersökningar släpps?

Just nu använder jag detta repo: https://github.com/hjnilsson/swedish-opinion-data 

Men datakvalitén på denna är mycket bättre, och det skulle fungera bättre som underlag. Är det möjligt att vi kan få bidra här?

**Comment by MansMeg** [comment]
Superbra idé! Det var min tanke från början. Ju fler som hjälps åt desto bättre.

Dock är jag skeptisk att ge fulla rättigheter direkt till personer jag inte träffat - särskilt eftersom vi kommer bygga sajt mot repot också. Jag förstår dock att ni vill kunna köra era sajter direkt vid uppdateringar.

Antingen kör vi på att ni bygger era sajter mot SwedishPolls-repot och gör Pull Requests. Jag brukar mergea dessa inom någon timme.

Alt. forkar ni repot och bygger era sajter mot egna forks. När ni gör en uppdatering så skickar ni en Pull Request så håller vi repot uppdaterat, men ni behöver inte "vänta in mig".

Vad tycks?

**Comment by hjnilsson** [comment]
OK.

Förstår inte riktigt varför vi inte kan bidra direkt hit. Vad tänker du det skulle göra för skada?

I vilket fall har jag skapat en fork här: https://github.com/hjnilsson/SwedishPolls

Jag kommer uppdatera den framöver, och gör mer eller mindre regelbundna pull requests hit helt enkelt.

**Comment by MansMeg** [comment]
Jag tror inte ni medvetet skulle försöka förstöra. Men ibland bygger man på olika sätt. Din förändring av FP-L skulle kunna pajja för oss men inte för dig. Men har vi varsin fork är riskerna minimala och möjligheten att dela (nästan) exakt lika bra.

Då är det bättre att börja samarbeta med forks. Forks är också ett snyggt alternativ till att jobba med branches i samma repo, vilket vi på sikt hade behövt göra.

**Comment by MansMeg** [comment]
Jag har nu fixat lite med detta repo, så nu är det än enklare att hämta data till R (via ett paket). Samt är en del polls uppdaterade/buggfixade liksom att allt ligger på Travis nu med löpande checkar.

Håll tillgodo!
