### ISSUE TITLE
Add data for Others

### ISSUE THREAD

**Issue by tommiehansen** [MansMeg/SwedishPolls#90]
Add column and data for the faux party `OTH` (others) where available. This since it could be considered an interesting value to follow/use for some purpose.

Currently the mergescript for Wikipedia could be used for such a thing since Wikipedia has a lot of data for others and the 'merge'-stuff automatically adds that column.

**Comment by MansMeg** [comment]
I have intentionally let that one out since it is easy to calculate when you want to use the data.

**Comment by tommiehansen** [comment]
And you're sure that this always adds up ie that there are no errors within data for unknown reasons etc?

**Comment by MansMeg** [comment]
Yes. I have a test suite that runs and check that it is allways >= 0 and I think less than 0.05/5%. So there are checks for this.

**Comment by tommiehansen** [comment]
oh, ok. Maybe it's uncessecary then. Will remove from PHP-stuff.
